generate_concept:
  description: >
    Generate a unique, innovative, eye-catching and marketable digital art concept.
    Your output should include a detailed breakdown of the concept with explicit elements such as:
      - Composition elements in short details
      - Narrative or thematic elements that resonate with a specific target audience.
      - Determine the best aspect ratio for this concept: "portrait" (2:3) or "landscape" (3:2)
        based on the composition and visual impact of the concept.
    Provide the output in a structured JSON format with keys: "style", "theme", "target_audience", and "aspect_ratio".
    For aspect_ratio, specify either "portrait" or "landscape" based on which would best showcase the concept.

    IMPORTANT: After generating the concept, you MUST save it as a JSON file using the JsonSaveTool.
    There are two ways to do this:

    Option 1 (Preferred): Pass your concept JSON object directly to the JsonSaveTool with the filename:
    ```python
    from etsy_listing_creator.tools import JsonSaveTool

    json_saver = JsonSaveTool()
    concept_json_path = json_saver.run({
        "data": your_concept_json_object,  # Your generated concept as a dictionary
        "filename": "output/concept_data.json"  # Save to this specific path
    })
    ```

    Option 2: If you encounter any errors with Option 1, you can also try passing your concept JSON object directly:
    ```python
    from etsy_listing_creator.tools import JsonSaveTool

    json_saver = JsonSaveTool()
    your_concept_json_object["_filename"] = "output/concept_data.json"  # Add a filename hint
    concept_json_path = json_saver.run(your_concept_json_object)
    ```

    Make sure to include the saved file path in your response so it can be used by subsequent tasks.
  expected_output: >
    A comprehensive JSON-formatted description of the art concept including detailed keys for style, theme, target_audience, variations,
    and aspect_ratio (either "portrait" or "landscape"), alongside a brief narrative explanation of the concept.
    The concept should be saved to a JSON file and the path to this file should be included in the response.
  agent: idea_generator

create_prompt:
  description: >
    Transform the previous art concept into a highly detailed, structured prompt for Stability AI's Flux model: 
    Details: [Brief, vivid description of key elements of the concept]
    Style: hyper-realistic, digital watercolor, minimalist (choose one or combine as needed)
    Use concise, comma-separated phrases for optimal T5/CLIP parsing. 
    Stick to indigo blue and honey orange colors theme since it's our shops niche
    Make sure to include "Style of TOK, indigo blue and honey orange colors" at the end of the prompt as plain text

    IMPORTANT: Extract the aspect_ratio from the concept (either "portrait" or "landscape") and include it in your output.
    Your output should be a JSON object with two keys:
    - "prompt": The well-structured text prompt for image generation
    - "aspect_ratio": The aspect ratio from the concept (either "portrait" or "landscape")
  expected_output: >
    A JSON object containing:
    - "prompt": A well-structured text prompt that includes all technical and stylistic details required for high-quality image generation
    - "aspect_ratio": The aspect ratio from the concept (either "portrait" or "landscape")
  agent: prompt_engineer

generate_image:
  description: >
    Utilize Replicate AI to generate a high-quality digital art image based on the detailed prompt.
    Include instructions for fallback regeneration if the output does not meet quality standards.

    IMPORTANT: Extract both the prompt and aspect_ratio from the prompt_engineer's output.
    The prompt_engineer provides a JSON object with "prompt" and "aspect_ratio" keys.
    Use the exact prompt from the "prompt" field, and pass the "aspect_ratio" value to the ReplicateTool.

    When using the ReplicateTool, provide the aspect_ratio parameter in your JSON input:
    {
      "prompt": "the prompt text",
      "aspect_ratio": "portrait" or "landscape"
    }
  expected_output: >
    A high-quality image that satisfies the technical and aesthetic requirements,
    accompanied by a log detailing generation parameters (including the aspect ratio used) and any quality assessments.
  agent: image_generator

research_seo:
  description: >
    Perform comprehensive keyword research and competitive analysis to optimize the Etsy listing.
    The output should include:
      - A ranked list of 13 effective keywords based on search volume and relevancy.
      - A suggested title that integrates high-impact keywords.
      - A detailed, SEO-friendly description tailored to attract the target audience.

    Title guidelines:
      - The title should be with this EXACT format: {2 words concept summary} | Indigo Bloom Downloadable PRINTABLE Digital | IB{Listing number}
      - An example for a correct title: "Futuristic Cityscape Art | Indigo Bloom Downloadable PRINTABLE Digital | IB12"

    Provide a brief rationale for each recommendation to demonstrate the analysis process.

    IMPORTANT: After generating the SEO data, you MUST save it as a JSON file using the JsonSaveTool.
    There are two ways to do this:

    Option 1 (Preferred): Pass your SEO JSON object directly to the JsonSaveTool with the filename:
    ```python
    from etsy_listing_creator.tools import JsonSaveTool

    json_saver = JsonSaveTool()
    seo_json_path = json_saver.run({
        "data": your_seo_json_object,  # Your generated SEO data as a dictionary
        "filename": "output/seo_data.json"  # Save to this specific path
    })
    ```

    Option 2: If you encounter any errors with Option 1, you can also try passing your SEO JSON object directly:
    ```python
    from etsy_listing_creator.tools import JsonSaveTool

    json_saver = JsonSaveTool()
    your_seo_json_object["_filename"] = "output/seo_data.json"  # Add a filename hint
    seo_json_path = json_saver.run(your_seo_json_object)
    ```

    Make sure to include the saved file path in your response so it can be used by subsequent tasks.
  expected_output: >
    A JSON structure containing:
      - "keywords": [array of optimized keywords],
      - "title": optimized title string,
      - "description": SEO-enhanced listing description.
    The SEO data should be saved to a JSON file and the path to this file should be included in the response.
  agent: seo_researcher

process_image:
  description: >
    Process the generated image to create multiple print-ready versions in standard sizes.

    IMPORTANT: The image_generator now provides a JSON output with both the image path and aspect ratio.
    You need to parse this JSON to extract both values. The output will look something like this:
    ```
    {
      "image_path": "output/images/replicate_generated_1234567890.webp",
      "aspect_ratio": "portrait" or "landscape"
    }
    ```

    DO NOT use the example paths shown in these instructions. You MUST extract the ACTUAL image path from the image_generator's output.
    The actual path will typically be something like "output/images/replicate_generated_1234567890.webp" with a timestamp.

    Steps include:
      - Automatically generating 5 standard print sizes based on the aspect ratio:
        - For portrait (2:3): 4x6", 5x7", 8x10", 11x14", 16x20"
        - For landscape (3:2): 6x4", 7x5", 10x8", 14x11", 20x16"
      - Maintaining aspect ratio while upscaling to each target dimension.
      - Ensuring 300 DPI resolution for all sizes.
      - Applying HDR and sharpness enhancements for optimal print quality.
      - Verifying image quality and dimensions for each size.

    When using the ImageProcessingTool, provide the aspect_ratio parameter in your JSON input:
    {
      "image_path": "THE ACTUAL PATH FROM THE IMAGE GENERATOR'S OUTPUT",
      "aspect_ratio": "portrait" or "landscape",
      "fill_canvas": true,
      "preserve_colors": true
    }

    The preserve_colors parameter (default: true) controls whether to preserve the original colors of the image:
    - always set to true to maintain the original colors while still making the image print-ready

    Each size will be processed with professional print standards and saved with a clear size indicator in the filename.
  expected_output: >
    A list of paths to the processed image files, one for each standard print size appropriate for the aspect ratio used,
    with verification of quality metrics, proper naming convention, and the aspect ratio used.
  agent: image_processor

create_mockups:
  description: >
    Generate high-fidelity product mockups that showcase the digital art in realistic, marketable contexts.
    IMPORTANT: Use the image generated by the image_generator agent (NOT the processed images).

    The image_generator now provides a JSON output with both the image path and aspect ratio.
    You need to parse this JSON to extract both values. The output will look something like this:
    ```
    {
      "image_path": "output/images/replicate_generated_1234567890.webp",
      "aspect_ratio": "portrait" or "landscape"
    }
    ```

    DO NOT use the example paths shown in these instructions. You MUST extract the ACTUAL image path from the image_generator's output.
    The actual path will typically be something like "output/images/replicate_generated_1234567890.webp" with a timestamp.

    The process should:
      - Dynamically overlay the generated art onto various scenes (e.g., framed on a wall, within a styled room setting).
      - Use the URL of the image from the image_generator's output directly.
      - Include detailed instructions for positioning, perspective, and environmental lighting to enhance realism.
      - Extract the aspect_ratio used by the image_generator and pass it to the DynamicMockupTool.

    When using the DynamicMockupTool, provide ALL required parameters in your JSON input:
    {
      "image_path": "THE ACTUAL PATH FROM THE IMAGE GENERATOR'S OUTPUT",
      "aspect_ratio": "portrait" or "landscape",
      "template_names": ["frame-mockup", "wall-art-mockup", "canvas-print-mockup", "poster-mockup", "living-room-mockup"]
    }

    The template_names parameter is REQUIRED and should include a list of template names to use for the mockups.
    Use the following template names based on the aspect ratio:
    - For landscape: ["landscape-frame-mockup", "landscape-wall-art-mockup", "landscape-canvas-print-mockup", "landscape-poster-mockup", "landscape-living-room-mockup"]
    - For portrait: ["portrait-frame-mockup", "portrait-wall-art-mockup", "portrait-canvas-print-mockup", "portrait-poster-mockup", "portrait-living-room-mockup"]

    Do not use any sandbox or placeholder images - only use the actual generated image from the previous step.
  expected_output: >
    A set of high-resolution mockup images accompanied by metadata in JSON format,
    detailing the context (e.g., indoor, outdoor, framed, unframed), the aspect ratio used, and any applied transformations.
  agent: mockup_generator

create_listing:
  description: >
    Create a complete Etsy listing based on the generated concept, image, SEO research, and mockups.
    Compile all the information into a structured format suitable for the Etsy API.

    IMPORTANT: Organize all files created in the workflow into a structured directory system:

    1. Use the FileOrganizerTool to create a structured directory system with subdirectories for each file and step of the workflow.
       The tool will create a main directory named with the listing name and timestamp, and subdirectories for:
         * concept/ - For concept information
         * original/ - For the original generated image
         * prints/ - For all print-ready versions
         * mockups/ - For all mockup images
         * metadata/ - For SEO and listing information

    2. Prepare a JSON object with the following structure to pass to the FileOrganizerTool:
       ```json
       {
         "listing_name": "Descriptive name based on the concept",
         "files": {
           "concept": ["output/concept_data.json"],
           "original": ["path/to/original_image.png"],
           "prints": ["path/to/print1.png", "path/to/print2.png", ...],
           "mockups": ["path/to/mockup1.png", "path/to/mockup2.png", ...],
           "metadata": ["output/seo_data.json"]
         },
         "cleanup": true  // Set to true to delete original files after copying
       }
       ```

    3. The FileOrganizerTool will:
       - Create a unique directory with the listing name and timestamp
       - Create all necessary subdirectories
       - Copy all files to their appropriate locations with meaningful names
       - Generate a manifest.json file documenting all organized files
       - Delete the original files after copying them (if cleanup is true)
       - Return the path to the organized directory structure

    4. Workflow steps for file organization:
       a. Collect all file paths generated during the workflow:
          - The concept JSON from the idea_generator (should be at "output/concept_data.json")
          - The original image from the image_generator (extract from JSON output - the actual path, not the example path)
          - All print-ready versions from the process_image task (the actual paths returned by the tool)
          - All mockup images from the create_mockups task (the actual paths returned by the tool)
          - The SEO information from the research_seo task (should be at "output/seo_data.json")
       
       b. Create a descriptive listing name based on the concept
       
       c. Organize the files using the FileOrganizerTool:
          ```python
          from etsy_listing_creator.tools import FileOrganizerTool
          
          # IMPORTANT: Use the ACTUAL file paths from the previous steps, not example paths
          organizer = FileOrganizerTool()
          organized_dir = organizer.run({
              "listing_name": "Descriptive Listing Name",
              "files": {
                  "concept": ["output/concept_data.json"],  # Use the saved concept JSON file
                  "original": [actual_original_image_path],  # Use the ACTUAL path from the image generator
                  "prints": actual_print_ready_paths,  # Use the ACTUAL paths from the process_image task
                  "mockups": actual_mockup_image_paths,  # Use the ACTUAL paths from the create_mockups task
                  "metadata": ["output/seo_data.json"]  # Use the saved SEO JSON file
              },
              "cleanup": true  # Delete original files after copying
          })
          ```

    5. CRITICAL: Create a comprehensive listing JSON with all details:
       - You MUST compile all the SEO data (title, description, tags) from the research_seo task
       - You MUST include pricing information based on print sizes and market research
       - You MUST add file paths to all assets (original, prints, mockups)
       - You MUST include any additional metadata for Etsy's API
       
       The listing JSON should include at minimum:
       ```json
       {
         "title": "SEO-optimized title from research_seo",
         "description": "Detailed description from research_seo",
         "tags": ["tag1", "tag2", ...],
         "assets": {
           "original": "path/to/original/image.png",
           "prints": ["path/to/print1.png", "path/to/print2.png", ...],
           "mockups": ["path/to/mockup1.png", "path/to/mockup2.png", ...]
         },
         "metadata": {
           "concept": { ... concept JSON ... },
           "aspect_ratio": "portrait" or "landscape",
           "style": "style from concept",
           "theme": "theme from concept",
           "target_audience": "audience from concept"
         },
         "directory": "path/to/organized/directory"
       }
       ```

    6. IMPORTANT: Save the complete listing information as a JSON file named "listing.json" in the metadata/ subdirectory.
       To save the JSON data, use the JSON Save Tool with the following format:
       - Pass the listing data directly as a dictionary (not as a string)
       - Use the path returned by the FileOrganizerTool + "/metadata/listing.json" as the filename
       
       Example:
       ```python
       from etsy_listing_creator.tools import JsonSaveTool
       
       json_saver = JsonSaveTool()
       listing_json_path = json_saver.run({
           "data": listing_data_dictionary,  # The complete listing information
           "filename": f"{organized_dir}/metadata/listing.json"
       })
       ```

    7. YOUR FINAL RESPONSE MUST BE THE COMPLETE LISTING JSON OBJECT, not just the path to the file.
       This ensures that all the listing details are properly included in the output.
  expected_output: >
    A comprehensive JSON object containing:
      - "title": optimized title,
      - "description": detailed listing description,
      - "tags": array of SEO-friendly tags,
      - "pricing": pricing details (if applicable),
      - "assets": { 
          "original": file links to original images,
          "printable": file links to print-ready versions, 
          "mockups": file links to mockup images 
        },
      - "metadata": additional details for listing optimization,
      - "directory": path to the organized listing directory.
    The JSON should be saved to the metadata subdirectory and the path to the organized directory structure should be included in the response.
  agent: listing_creator
