generate_concept:
  description: >
    Generate a unique, innovative, and marketable digital art concept.
    Consider seasonal influences, popular artistic styles, customer demographics, and emerging visual themes.
    Your output should include a detailed breakdown of the concept with explicit elements such as:
      - Suggested color palettes and stylistic references.
      - Narrative or thematic elements that resonate with a specific target audience.
      - Potential variations to adapt the concept for different customer segments.
    Provide the output in a structured JSON format with keys: "style", "theme", "target_audience", and "variations".
  expected_output: >
    A comprehensive JSON-formatted description of the art concept including detailed keys for style, theme, target_audience, and variations,
    alongside a brief narrative explanation of the concept.
  agent: idea_generator

create_prompt:
  description: >
    Transform the previous art concept into a highly detailed, structured prompt for Stability AI’s Flux model: 
    Details: [Brief, vivid description of key elements of the concept]
    Style: hyper-realistic, digital watercolor, minimalist (choose one or combine as needed)
    Use concise, comma-separated phrases for optimal T5/CLIP parsing. 
    Stick to indigo blue and honey orange colors theme since it's our shops niche
    Make sure to include "Style of TOK, indigo blue and honey orange colors" at the end of the prompt
  expected_output: >
    A well-structured, one sentence text prompt that includes all technical and stylistic details required for high-quality image generation,
    formatted in plain text and ready for direct input into Stability AI.
  agent: prompt_engineer

generate_image:
  description: >
    Utilize Stability AI to generate a high-quality digital art image based on the detailed prompt.
    Include instructions for fallback regeneration if the output does not meet quality standards.
  expected_output: >
    A high-quality image that satisfies the technical and aesthetic requirements,
    accompanied by a log detailing generation parameters and any quality assessments.
  agent: image_generator

research_seo:
  description: >
    Perform comprehensive keyword research and competitive analysis to optimize the Etsy listing.
    The output should include:
      - A ranked list of effective keywords based on search volume and relevancy.
      - A suggested title that integrates high-impact keywords.
      - A detailed, SEO-friendly description tailored to attract the target audience.
    Provide a brief rationale for each recommendation to demonstrate the analysis process.
  expected_output: >
    A JSON structure containing:
      - "keywords": [array of optimized keywords],
      - "title": optimized title string,
      - "description": SEO-enhanced listing description.
  agent: seo_researcher

process_image:
  description: >
    Process the generated image to create multiple print-ready versions in standard sizes.
    Steps include:
      - Automatically generating 5 standard print sizes (4x6", 5x7", 8x10", 11x14", 16x20").
      - Maintaining aspect ratio while upscaling to each target dimension.
      - Ensuring 300 DPI resolution for all sizes.
      - Applying HDR and sharpness enhancements for optimal print quality.
      - Verifying image quality and dimensions for each size.
    Each size will be processed with professional print standards and saved with a clear size indicator in the filename.
  expected_output: >
    A list of paths to the processed image files, one for each standard print size (4x6" to 16x20"),
    with verification of quality metrics and proper naming convention.
  agent: image_processor

create_mockups:
  description: >
    Generate high-fidelity product mockups that showcase the digital art in realistic, marketable contexts.
    IMPORTANT: Use the image generated by the image_generator agent (NOT the processed images).
    The process should:
      - Dynamically overlay the generated art onto various scenes (e.g., framed on a wall, within a styled room setting).
      - Use the URL of the image from the image_generator's output directly.
      - Include detailed instructions for positioning, perspective, and environmental lighting to enhance realism.
    Do not use any sandbox or placeholder images - only use the actual generated image from the previous step.
  expected_output: >
    A set of high-resolution mockup images accompanied by metadata in JSON format,
    detailing the context (e.g., indoor, outdoor, framed, unframed) and any applied transformations.
  agent: mockup_generator

create_listing:
  description: >
    Compile all generated content into a complete and ready-to-publish Etsy listing.
    The listing should include:
      - The optimized title, description, and tags from the SEO research.
      - All relevant images (printable PNG, PDF, and mockups) with their associated metadata.
      - Pricing suggestions if applicable, and any additional details needed for Etsy's platform.
    The final output should be a structured JSON object suitable for direct integration with the Etsy API.
    IMPORTANT: Save the complete listing information as a JSON file named "listing.json" in the output directory.
    To save the JSON data, use the JSON Save Tool with the following format:
      - Pass the listing data directly as a dictionary (not as a string)
      - Use "listing.json" as the filename (do not include "output/" in the filename)
  expected_output: >
    A comprehensive JSON object containing:
      - "title": optimized title,
      - "description": detailed listing description,
      - "tags": array of SEO-friendly tags,
      - "pricing": pricing details (if applicable),
      - "assets": { "printable": file links, "pdf": file links, "mockups": file links },
      - "metadata": additional details for listing optimization.
    The JSON should be saved to "output/listing.json" and the path to this file should be included in the response.
  agent: listing_creator
